# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
blogbaseurl: ""
images: "/blog/img"
url: "http://remidoolaeghe.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: On n'est pas que des codeurs
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "Le blog de Rémi Doolaeghe, freelance, sur l'agilité et le développement web" # used by search engines

  # Header and footer text
  header_text: >
     Actualités
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a>

  # Icons
  rss: false
  email_address: remi.doolaeghe@laposte.net
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "remidoolaeghe"
  google_plus:
  instagram:
  linkedin:  https://fr.linkedin.com/pub/rémi-doolaeghe/19/b49/327
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  http://stackoverflow.com/users/1844337/r%C3%A9mi-doolaeghe
  steam:
  tumblr:
  twitter: "remidoolaeghe"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: remidoolaeghe
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Suivez-moi sur"
  str_rss_follow: "Abonnez-vous au flux RSS"
  str_email: "Email"
  str_next: "Suivant"
  str_prev: "Précédent"
  str_continue_reading: "Lire la suite"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
permalink: /blog/:categories/:year/:month/:day/:title.html
paginate: 10
paginate_path: "remidoolaeghe/num"
paginate_category: "blog"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
