# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
blogbaseurl: "/blog"
freelanceurl: "/freelance"
images: "/blog/img"
skill_images: "/img/skills"
frontage_images: "/img"
url: "http://remidoolaeghe.github.io" # the base hostname & protocol for your site
encoding: utf-8

# metatheme-SPECIFIC CONFIGURATION
metatheme:
  # Meta
  title: On n'est pas que des codeurs
  avatar: avatar.jpg
  gravatar: # Email MD5 hash
  description: "Rémi Doolaeghe, freelance artisan du web et coah agile" # used by search engines

  # Header and footer text
  footer_text: Powered by <a href="http://jekyllrb.com">Jekyll</a>

  # Icons
  rss: false
  email_address: remi.doolaeghe@gmail.com
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "remidoolaeghe"
  google_plus:
  instagram:
  linkedin:  http://www.linkedin.com/in/remidoolaeghe
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  http://stackoverflow.com/users/1844337/r%C3%A9mi-doolaeghe
  steam:
  tumblr:
  twitter: "remidoolaeghe"
  wordpress:
  youtube:

  # Scripts
  google_analytics: UA-65732371-1
  disqus_shortname: remidoolaeghe
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Suivez-moi sur"
  str_rss_follow: "Abonnez-vous au flux RSS"
  str_email: "Email"
  str_next: "Suivant"
  str_prev: "Précédent"
  str_continue_reading: "Lire la suite"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
permalink: /blog/:categories/:year/:month/:day/:title.html
paginate: 10
paginate_path: "blog/:num"
paginate_category: "blog"
gems: [jekyll-paginate]

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
